menu:
  Home: /
  Archives: /archives

widgets:
- search

cover:
  enable: true
  url: http://ww3.sinaimg.cn/large/71ec623cgw1f1n8lsdmq0j21kw16ojy2.jpg
   
excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: true
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

google_analytics: UA-368771XX-X
rss:

comment_provider: duoshuo

# Duoshuo comment
duoshuo:
  short_name: your_id

social:
  github: https://github.com/szitguy
  weibo: http://weibo.com/1911317052
  google_plus: https://plus.google.com/u/0/110628197979019081918

auto_change:
  enable: true
